### ISSUE TITLE
Separate compute + storage config for bakeries

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/pangeo-forge-orchestrator#117]
@sharkinsspatial and I discussed today his plans to write to multiple Dev Seed client locations from the same compute.

To avoid duplication in config, this use case would be served by separating compute and storage config for bakeries.

These storage targets could then be specified in `meta.yaml`:

```yaml
bakery:
  id: "pangeo-ldeo-nsf-earthcube"
  target: "osn"
```
